jadijadi/lpic1book

- 1011_determine_and_configure_hardware_settings.md
- 1012_boot_the_system.md
- 1013_change_runlevels_and_shutdown_or_reboot_system.md
- 1021_design_hard_disk_layout.md
- 1023_manage_shared_libraries.md
- 1024_use_debian_package_management.md
- 1025_use_rpm_and_yum_package_management.md
- 1031_work_on_the_command_line.md
- 1032_process_text_streams_using_filters.md
- 1033_perform_basic_file_management.md
- 1034_use_streams,_pipes_and_redirects.md
- 1035_create,_monitor_and_kill_processes.md
- 1037_search_text_files_using_regular_expressions.md
- 1041_create_partitions_and_filesystems.md
- 1042_maintain_the_integrity_of_filesystems.md
- 1043_control_mounting_and_unmounting_of_filesystems.md
- 1044_manage_disk_quotas.md
- 1045_manage_file_permissions_and_ownership.md
- 1046_create_and_change_hard_&_symbolic_links.md
- 1047_find_system_files_and_place_files_in_the_correct_location.md
> fix some typos

- 1011_determine_and_configure_hardware_settings.md
Hey there, I didn't know if there was any purpose of putting ending dots; so they've been removed.
> Fixing some minor typos on 101.1

- 1042_maintain_the_integrity_of_filesystems.md
> Fixed typo

- 1033_perform_basic_file_management.md
> correct html's spelling

- content/1011_determine_and_configure_hardware_settings.md
Hey @jadijadi,
I just fixed some typos and markdown styles.
> Fix typos on chapter 101.1

- theme/elegant/templates/base.html
fixes #46 
redirect to google on search
> redirect to google on search

- content/1044_manage_disk_quotas.md
Hi @jadijadi . All chapters with a **Work in Progress** description, have a typo error like this (line 13 on this PR). It's just a sample.
> Fix 1044 typo

- content/1021_design_hard_disk_layout.md
as these drives are getting popular (for example mmc storage on raspberry pi or nvme devices for newer and faster storages on pci express) these descriptions  should  be in LPIC so if I learn from this book I can also use these devices
> nvme and mmc storages added to hard disk layout section

- content/1023_manage_shared_libraries.md
> Chapter 102.3

- content/1026_linux_as_virtualization_guest.md
> typo: fix some typo

- content/1032_process_text_streams_using_filters.md
> Minor typo fix in 1032

- content/1032_process_text_streams_using_filters.md
these have been changed :
* Grammatical and some words spelling fixed.
* Added some `</br>` tag to beautify.
* Added `N` option to the table in seds search section.
> Typo: Some Typo Fixed in 103-2

- content/0002_prepare-lpic101-102-lab.md
- content/1011_determine_and_configure_hardware_settings.md
- content/1012_boot_the_system.md
- content/1013_change_runlevels_and_shutdown_or_reboot_system.md
- content/1021_design_hard_disk_layout.md
- content/1022_install_a_boot_manager.md
- content/1023_manage_shared_libraries.md
- content/1024_use_debian_package_management.md
- content/1025_use_rpm_and_yum_package_management.md
- content/1031_work_on_the_command_line.md
Hi@jadijadi,
I've just fixed the recent messed-up #67 PR:
- Fix grammatical issues
- Change markdown styles
- Fix headers hierarchical format
> Minor changes up to chapter 103.1

- content/1033_perform_basic_file_management.md
changes : 
1. Some Typo fixed
2. Some Sentences have been changed for clarity
3. Headings added to be able to hyperlink them in the book
4. Code blocks added for a few commands like `ls` and others
5. and some other minor changes.
> Typo : Fix Some Typo

- content/1034_use_streams_pipes_and_redirects.md
Changes : 
1. Some typo Fixed 
2. Italic words chaged to both italic and strong(Bold)     
3. switches of `xargs` have changed to be an ordered list
> Fix : Some Typo fixed in 103.4

- content/1035_create-_monitor_and_kill_processes.md
The Changes have been applied :
1. Add Youtube videos link to the book
2. Align some of the left sides of the tables in the middle 
3. Fix Some Typos and grammatical issues
> Typo : Fix Some Typo  and Youtube links add in 103.5

- content/1103_securing_data_with_encryption.md
I fixed some grammar, spelling and style issues.
> Fix grammar, spelling and style

- content/1037_search_text_files_using_regular_expressions.md
Some `</br>` tags were added to make more space between tables and text.
Some dotes `.` were added at the end of the sentences.
> Fix: Some Typo in 1037 file

- content/1024_use_debian_package_management.md
> Corrected a typo

- content/1041_create_partitions_and_filesystems.md
- content/1042_maintain_the_integrity_of_filesystems.md
changes:
1. add `swapon` for making swap partitions at the end. 
2. fix some typos and wrong words.
3. align to the center in the table of partition types.
> Fix: some typo and minor changes

- content/1046_create_and_change_hard_and_symbolic_links.md
In line 26:
1. save :point_right: saved
2. black :point_right: block
3. is :point_right: it
In line 120:
4. `unlnk` :point_right: `unlink`
> Corrected four typos in two lines

- content/1033_perform_basic_file_management.md
- content/1071_manage_user_and_group_accounts_and_related_system_files.md
div bugs in content, details see commit messages
> bugs in chapters 1033 and 1071

- content/1084_manage_printers_and_printing.md
- content/1091_fundamentals_of_internet_protocols.md
Changes: 
- Add Youtube Iframe to part 1084
- Add Youtube Iframe to part 1091
- Fix Some typos in 1091
- Align The port number table to the center at line 228 in 1091
> Update: Add Youtube iframe to 1084 and 1091

- output/theme/css/custom.css
- theme/elegant/static/css/custom.css
hi, thanks for LPIC 1
[linux1st.com](https://linux1st.com/) has a problem in displaying on small screens such as mobile 
YouTube section is not responsive
i was try to solve this
> fix youtube in small screen

- content/1013_change_runlevels_and_shutdown_or_reboot_system.md
fixed #112 issue base on YouTube video
> #112 issue

- content/1011_determine_and_configure_hardware_settings.md
- content/1012_boot_the_system.md
- content/1013_change_runlevels_and_shutdown_or_reboot_system.md
- content/1021_design_hard_disk_layout.md
Fixing grammatical errors for an easier read.
> Fixing typos, Grammar errors and adding minuscule info

- content/1035_create-_monitor_and_kill_processes.md
Changed the following 
"tells to process to terminate itself" to this "tells the process to terminate itself"
> Fixed a wrong word in 1035
